### ISSUE TITLE
HTML Structure

### ISSUE THREAD

**Issue by meganspaulding** [MeganSpauldingCreative/GWG-animal-card-generator#6]
Since Dima has got us started with our HTML structure already, I am going ahead and opening an issue for HTML. 

Once we have finalized our wire frame I will create a master HTML file.

Let’s hold off on styling for now, and just get the necessary HTML pieces in place so that we’re not working on top of each other too bad!

**Comment by meganspaulding** [comment]
If there is some basic styling needed to make the HTML make sense that is fine!

**Comment by dimakm** [comment]
Megan, I saw the wire frame you posted about how things will look like,and started to put pieces together in my mind to know what to do, I made a button (Add card) when we click we get a popup form where we can fill the information for the new card, here's the cod pen for it: 
https://codepen.io/Dima-KM/pen/VXaXKv 

My question is about the (Edit card) button , if we want to edit cards that means we are already saving the cards somewhere, which means we need to use database to save the information the we want to retain and edit, are we going to use database here!! or there's another way to do that?

**Comment by stealing-pencils** [comment]
These look fantastic already! I think the form Dima, is great and the wireframe files already look brilliant Megan. I was wondering, whether it's worth laying out the objective of these cards i.e. if they're meant to be educational or entertaining etc? Who are they meant to be for? I only ask because that may change the way we present them. If they're for kids, then they can be presented in a simpler / cute style, whereas if they're more for entertainment purposes, they could be more jokey with an 'Exploding Kitties' type look.

Separately, Megan when you included the 'add', 'delete' and 'edit' features, were they to provide the user with the means of 'adding' another card, 'deleting' a card from their collection and finally 'editing' a card? I wasn't quite sure what they were going to edit. I totally get the add and delete buttons, but just wanted to make sure I was on the same page with edit. Thanks!

**Comment by meganspaulding** [comment]
@dimakm For the edit button, it is just for practice. We should be able to edit cards added before the page is refreshed. Like if I input a card for a dog but realized it was a picture of a cat and wanted to edit it real quick. So not pulling from past cards, just cards from within the current use. 

@stealing-pencils My idea was the purpose of this project would be for educational purposes to demonstrate the reusability for CSS classes, so I was just thinking clean and nice, like Udacity. But what do you think? 

And to answer your second question, yes. Edit was more to practice javaScript than anything, as this isn't actually a functional page that holds much worth other than for our learning purposes since we can't permanently save any cards without backend.

**Comment by meganspaulding** [comment]
@dimakm I love where you are going with the modal, great work! I am wondering what all of the script tags are for? It's causing a slow load time for me. I'm also not sure how easily that modal will be able to be edited in CSS as is, do you have an experience manipulating these jquery themes? Do you think it might be simpler and more flexible to build the modal with an HTML div, and open and close it using "toggle class?" That should also help speed up load time. This is how I build my modals for my final project. What do you think?

**Comment by dimakm** [comment]
@MeganSpauldingCreative I totally agree with you, I used Jquery UI that's why I have all the scripts tags.
The way you built your modals is a great Idea , I didn't think of it.

**Comment by stealing-pencils** [comment]
That sounds great @MeganSpauldingCreative.  Would it be worth constructing some kind of flow chart to outline the options users would be given on the website (along the lines of @dimakm's form) and the animal cards that would be created as a consequence?  Hopefully that makes sense!

**Comment by dimakm** [comment]
Today I worked on the card html, I canceled the changes made yesterday and instead I added a class to the card so we can later work on toggling the class as @MeganSpauldingCreative mentioned yesterday, I added some Css because I really don't like to see a messy card, I am an artist and love things to look good :) so I made it somehow organized.
I also added the (upload image) in the card, I had to use a link to a script from jquery for this but if you have a way to upload image without the jquery it would be great.
here's the codepen:
https://codepen.io/Dima-KM/pen/aYdYdo

**Comment by dimakm** [comment]
@MeganSpauldingCreative  hi, anything new?

**Comment by meganspaulding** [comment]
It’s been a packed couple of days!

@stealing-pencils yes! A flow chart would probably be good! Would you want to try and get that together? 

@dimakm I haven’t had a chance to look at your updated code, but will be able to tomorrow! 

Sorry for the short delay! We have guests in from out of town.

**Comment by meganspaulding** [comment]
Our HTML team is @dimakm and @YOURsammich... 

@dimakm The new form looks great!

@YOURsammich would you like to check out Dima's code for the form, and make edits? There are a few things I noticed that can be changed, such as an extra div. I wanted to give you a chance to edit before I did. If you don't get to it today, I will probably go in tomorrow to edit so that we can stay on course! 

Do you guys want to start building out the  HTML for the actual page? Let's try to have this done by the 20th if possible to stay on schedule!

**Comment by meganspaulding** [comment]
Also! @dimakm @YOURsammich @stealing-pencils I have now added in the html, css, and js files for this project which include Dima's code, so you can now make commits on them! Sorry, I didn't think about doing that earlier.

**Comment by YOURsammich** [comment]
@MeganSpauldingCreative Hey I think you may of forgotten to sync your changes with the repo, I'm not seeing the new files

**Comment by stealing-pencils** [comment]
I can't see them either I'm afraid - really looking forward to seeing them though!  

I can work on a flow chart today.  So would it simply be a case of the user inputting the details of the animal based on @dimakm's form?  Then that information would populate the animal card?  I'm just wondering how we're going to work the animal pictures into this.  Let me know if I've got the wrong end of the stick.

Thanks!

**Comment by meganspaulding** [comment]
Sorry about that guys! It is populated now! 

@stealing-pencils I guess it would be inputing information intially, adding a card later, editing a card, and deleting a card. @dimakm found a bit of code that allows people to upload photos to use for the card,  but if that doesn't work we can just have them put in the address of an image to use it.

**Comment by YOURsammich** [comment]
@dimakm I got the image uploading working without jQuery, you pretty much had it, I just swapped out the parts of the code that were jQuery and replaced it with plain JS

**Comment by stealing-pencils** [comment]
That's awesome about the image uploader.  Maybe if there's a problem with the image uploader e.g. the user makes a mistake or typo - we could have a fall-back fun image that could be displayed as a default? Or do you guys think that would be unnecessary?  I'd be happy to mock something up if that would be useful.

**Comment by YOURsammich** [comment]
@stealing-pencils Yeah we could use a fall back image, We could also use it if the user makes a new card and forgets or just doesn't want to upload a picture.

**Comment by meganspaulding** [comment]
Hey everyone! I just closed the Wireframe issue so we only have 1 line of communication... If you need to reference it, you can view it under closed! 

I went in and did a major re-haul on our code organization, please try to keep everything as organized as possible, with more than one cook in the kitchen things can get messy fast!

Somehow we accidentally ended up with two .js files. Please note that the SCRIPT file is what is linked to our HTML.

I have left everything that was on the file that was not linked where it was, and renamed that file "scratch pad", so that we can pull from what has been written already when we need it. 

Let's focus on making sure our page is up and running, before adding functionality to our card generator, so that we can make sure everyone is on the same page, and that we have a solid base.

Other than adding in more styling, what else can we accomplish for overall page functionality before going in to make our input's functional? Is there anything missing?

I will be getting together a list of action items tomorrow for us to keep organized with as well! 

Great work guys! You guys are awesome!

**Comment by stealing-pencils** [comment]
This really does look absolutely awesome!  The only other functionality that you might want to add to the card is a general description box.  I don't think it's essential, but if the user wanted to add their own description, especially if it's a fictional / cartoon animal card, that might be fun.  I'm not sure if it would be more hassle than it's worth though..?

**Comment by stealing-pencils** [comment]
Thanks for your input on the fallback image @YOURsammich - appreciate this is way down on the list of things to do, but I can create something and present it to you guys later.  I won't muddy the waters and add this to the to-do list when as @MeganSpauldingCreative said, there are many more essential things to do first.

**Comment by YOURsammich** [comment]
@MeganSpauldingCreative I agree with @stealing-pencils I think we need a textarea on the card for general description.

Also I was thinking that one way we could show off why CSS classes are awesome is with different card themes, the user could just select a theme from a drop down box and each theme is really just a different CSS class. Perhaps a dark and a light theme for starters, and we can use JavaScript to apply these themes in real time as the user hovers over the options.

Let me know if you guys think that's a good idea.

**Comment by brentrain** [comment]
I added a background color.  I know its not a lot, but right now I dont really understand git and github very well - how can I see the site in full?

**Comment by stealing-pencils** [comment]
Love that idea of different card themes @YOURsammich!

**Comment by stealing-pencils** [comment]
Hey @brentrain, @MeganSpauldingCreative has provided a great list of resources for git / github on the README page.  I'm really new to github too, so you're in good company!

**Comment by meganspaulding** [comment]
Hey everyone! I have made a new file called "actionItems" that we can use for a checklist. Please go and add any action items that you see are missing! 

Do you think it would be helpful to assign specific items to people? And then we can edit their base? Or would that be more annoying than helpful? Can you tell I'm a little type A yet? Haha! 

@YOURsammich I love that idea too! What if we did a drop down menu of habitats and based the style of the card on the habitat of that animal? This was what I did for my animal card project: https://codepen.io/meganspaulding/pen/MrzepM ... Maybe something like that? Or would that get out of hand? Haha! What do you guys think?

Hi @brentrain Welcome! I echo what @stealing-pencils said! Check out the ReadMe, and sign up for any teams you would like to be a part of. To view the site, you just open the HTML file that you clone from this repository in your browser, just as you do with local files for the class!

I do not see a pull request from you, so your background change has not been applied to the project as a whole. The sign up form is a great way to practice doing a pull request that I can then merge your changes into the project. If you are having trouble figuring that out, please shoot me a DM on slack @Megan Spaulding and I will be happy to help!

**Comment by meganspaulding** [comment]
Also @brentrain make sure you click "watch" so that you can get notifications as the project progresses.

**Comment by YOURsammich** [comment]
@MeganSpauldingCreative I think basing the cards theme on the animals habitat is a great idea, won't take up anymore space on the card maker panel too.

Also I think assigning specific task to people would be good that way two people aren't working on the same thing.

**Comment by dimakm** [comment]
I love the idea of having themes as @Yoursammich said, and I love the idea of making the theme changes depending on the habitat .
I’ll look at the actioitems file

**Comment by meganspaulding** [comment]
Cool! I went ahead and took the liberty of assigning a couple things, just to get the ball rolling... 

@dimakm would you mind making the edits to the modal?

@YOURsammich would you mind setting up the HTML for a temporary card? I have created a file for this purpose.

I think once we have that, we will be ready to lean into some styling before taking off with javaScript! 

@stealing-pencils be thinking of whether there are are CSS action items specifically that you want to work on!

**Comment by stealing-pencils** [comment]
Hi @MeganSpauldingCreative - assigning tasks per person is a great idea.

I'm happy to work on any CSS that will be helpful.  @MeganSpauldingCreative, I was wondering if you prefer to work on the general look / design of the page and I can work on specific items that will be helpful, but also won't overlap with you.  For example, I can create the habitat backgrounds for the cards as @YOURsammich suggested.  I can also create a place holder image for the card if the user hasn't uploaded their own photo.  Happy to do something else if you think it would be more useful, but this is what springs to mind.

**Comment by dimakm** [comment]
@meganspauldingcreative yes I’ll work on the modal, I’ll start tomorrow because I’m out of town today without my laptop

**Comment by meganspaulding** [comment]
@stealing-pencils that sounds great! It looks like @YOURsammich got the HTML done for the temp card for us to use. I will work on some CSS tonight to give us a base and touch back here to talk next steps.

@dimakm no problem! Take your time!!!

**Comment by stealing-pencils** [comment]
Sounds great @MeganSpauldingCreative!  I'm working on the card background using pure CSS - just very simple images as backgrounds for the different card themes.  Does that sound OK?

**Comment by dimakm** [comment]
Good morning mates, 
I made the modal updates last night and sent a pull request . Let me know if anything needs to be changed.

**Comment by brentrain** [comment]
May I contribute to this project?

**Comment by meganspaulding** [comment]
@brentrain Yes you can! I don't know if you saw our previous replies to your last post, but you will first have to sign up for a team. This is really just to make sure you are properly set up to contribute, and for me to know what you want to help with! Please note that the HTML Structure has already been completed and the bulk of what is left is CSS & JavaScript... If you read the "readme" file on this project, it has the instructions on how to do this.

As soon as I know what teams you would like to be on, I can give you more direction on how you can help!! 

If you have any trouble signing up, please message me on slack @Megan Spaulding

**Comment by meganspaulding** [comment]
@stealing-pencils That sounds great!!

Great work getting our HTML all set up @dimakm & @YOURsammich -- You guys are awesome!

I have started designing the main page. Haven't finished yet, but let me know what you think of the direction. 

I added a + to the upper hand corner, because I had this realization that when someone adds more than like 3 cards, that the blank + would get pushed down to where they couldn't see it anymore. What do you guys think about that? Like it? Don't like it?

Side note, you guys are just so awesome. Everyone has done such an awesome job of sharing the load! Glad to be working with you all!

**Comment by dimakm** [comment]
@MeganSpauldingCreative You are awesome and I’m glad to be working with you and the other project mates too.

It is a smart idea to put the + to the upper corner, I like it.

**Comment by stealing-pencils** [comment]
I think that's a great idea @MeganSpauldingCreative - really glad to be part of this team.  I've created the bird habitat background.  I'm working on making the code more concise @MeganSpauldingCreative, @dimakm, @YOURsammich and @brentrain.  Here's the codepen:  https://codepen.io/ksmiddy/pen/GxmQNr in the meantime!

**Comment by YOURsammich** [comment]
I like that card @stealing-pencils however i'm confused on one thing.
So like in the code are we gonna style the card by selected animal group or selected habitat?
Because on the card for habitats we have "Rain Forest, Forest, Desert, Marine, Polar, Savanna, Fresh Water, Farm" 

@MeganSpauldingCreative I like how the main page looks. It'd be nice if the + symbol looked more "clickable" though. perhaps if it had a rounded border something like this? https://i.imgur.com/fOim2c8.png

Also i'm happy to be working with you all too 😄

**Comment by stealing-pencils** [comment]
Hey @YOURsammich - I should have said I was basing it on the animal type rather than habitat, that was my mistake.  I looked at this again and realised that I was working off of the old card habitats, when there were fewer of them!  In the interest of time, I'll simply create themed modal color background rather than try and create CSS illustrations for each of the cards (maybe if there's time I could work on this later).  I'll get going on this today.

**Comment by YOURsammich** [comment]
No worries @stealing-pencils just making sure we're all on the same page.

**Comment by meganspaulding** [comment]
@YOURsammich great idea!!! 

@stealing-pencils awesome job!

We have been out of town this weekend, but I will be updating everything and everyone tomorrow, along with updating the schedule!

**Comment by meganspaulding** [comment]
@brentrain Did you ever figure out how to sign up? Again, feel free to message me on Slack!

**Comment by stealing-pencils** [comment]
Hey @MeganSpauldingCreative - I've created the color palettes for each of the animal cards (based on habitat) and have written the CSS for each theme.  I haven't started adjusting the text positioning / buttons etc because I don't want to step on your toes.  I want to check-in with you first about:
1. whether you would like me to add CSS to the user input modal (.new-card-modal)?  In other words, 
    I'm guessing this should be a standard color scheme / look which ties into the rest of the website?
2. if you would like me to work on the design of the animal cards themselves.  

I just realised that you'll have a specific look / color palette / typeface that you'll want me to follow and won't want me going off making cards that don't fit with the website look you have created! Thanks!

**Comment by meganspaulding** [comment]
@stealing-pencils Sorry for the delay! My kids have been going a little crazy getting readjusted after vacation. 

I'd love to see what the CSS for the themes is. Where is that living? 

I am currently working on the modal styling since it ties into the whole page. I have a header font already applied, but let me upload a body font. And I also will link shortly with an overall color scheme.

@YOURsammich I think we could probably start writing the javascript, don't you think? Our base is there. Do you want to start writing the code for adding new cards?

**Comment by meganspaulding** [comment]
@stealing-pencils Here is a link to the base color scheme. 

https://coolors.co/1e5799-23bfea-addfed-f2f2f2-424242

The fonts are nunito for headers and open sans for body :)

**Comment by stealing-pencils** [comment]
Hey @MeganSpauldingCreative - tell me about it.  I have four month old who is doing some sleep regression business I didn't sign up for!  You have my complete sympathy!

So I uploaded the card habitat themes as a separate file, (styles_card_themes.css), only because I thought it would be best to keep them separate until the basic animal card structure is settled on.  As a stop-gap, if you use the .new-card-modal and h3 code, you'll be able to see the background / font colors.  When you say you're working on the modal styling, shall I just hold back until you're done with that?  Then I can apply the background colors and any extra styling?  Or would you like me to start work on the animal card itself too?  I hope I'm helping you here, I feel like I might just be making your job harder at the moment.

**Comment by YOURsammich** [comment]
@MeganSpauldingCreative Sure i'll start on the JavaScript.
I'v noticed an issue with the modal is that its long enough to go off the screen and I can't scroll down because its using fixed positioning, do you mind if i change some elements to absolute positioning in the CSS so it doesn't scroll with the page, like the close button and the + button on the header?

**Comment by YOURsammich** [comment]
@MeganSpauldingCreative Sure i'll get started on the JavaScript

**Comment by brentrain** [comment]
I have no idea how to sign up.  I also have no idea where to begin.  I have some ideas, but nowhere to start with them...first things first, how do I sign up?

Brent

**Comment by YOURsammich** [comment]
@brentrain Do you have GitHub desktop installed?

@MeganSpauldingCreative I got the JavaScript done for adding a new card but i noticed there isn't really any CSS class i can give it ready yet, do you mind if i help out with the CSS too?

**Comment by stealing-pencils** [comment]
Hey @YOURsammich and @MeganSpauldingCreative - I'm just adding a CSS class for a completed animal card right now.  I want to get it done by the end of the day for you @YOURsammich.  I went about this backwards, creating the animal card habitat themes before actually writing code for a basic completed card.  If I power ahead with this, would that work for you @YOURsammich and @MeganSpauldingCreative ?

**Comment by YOURsammich** [comment]
@stealing-pencils The CSS for a basic card? Yeah that works for me

**Comment by brentrain** [comment]
yes I have GitHub, is there a signup area there?

**Comment by meganspaulding** [comment]
@brentrain if you click the "code" tab, you will see a "readme" file... That file has instructions on how to sign up. You will need to sign up this way, because it teaches you how you have to contribution using pull requests. Please message me on slack @Megan Spaulding if you have any trouble figuring it out!

I do want to note, however, that there is not much work left to be done, so if you can't figure out the pull request process with github, perhaps you can help us in testing, which will be run through comments like this thread!

**Comment by meganspaulding** [comment]
@dimakm @stealing-pencils @YOURsammich @brentrain this issue has gotten long, so I am going to go ahead and close and open a new one!

**Comment by brentrain** [comment]
That sounds good to me. I’ll get signed up

**Comment by brentrain** [comment]
Ive done everything that I know how to to sign up, but no luck.
so if you still need me to test perhaps some more detailed insturctions on
howto add the upstream thing
 I've got some ideas I'm working on that I think are great and I'll work on
those in the meantime

brent
